### ISSUE TITLE
Pagespeed insights

### ISSUE THREAD

**Issue by bwc69151** [SLorant/Snowy-Snaps#1]
Some recommendations worth looking at https://pagespeed.web.dev/analysis/https-snowy-snaps-web-app/xzahodiryb?form_factor=mobile

**Comment by SLorant** [comment]
Thank you for this! It's interesting that the mobile version is a lot slower. I will change image formats to webp, and split the code. Then if the speed improves (to an acceptable amount) I will close this issue.

**Comment by SLorant** [comment]
I've managed to double the speed in mobile with some image optimization / code splitting. Still not the best, but the google font is necessary, and the site is big, so there will always be unused Javascript. I close this issue for now. Here is the new pagespeed test: https://pagespeed.web.dev/analysis/https-snowy-snaps-web-app/4tlwbbwmn5?form_factor=mobile
