### ISSUE TITLE
Gallery modal dates broken (clipping)

### ISSUE THREAD

**Issue by SharmaMitchell** [SLorant/Snowy-Snaps#2]
Dates in the gallery modal are being cut off, ex. "4/8/2023, 1:" or "4/1/2023, 11" because of the substring operation here:
https://github.com/SLorant/Snowy-Snaps/blob/93c3f188a00ca79c83fc4de223397831718b7894/src/components/gallerycomp/Modal.jsx#L22

Suggested fix: show full date without using substring, or (if the goal of substring here was to cut off the seconds) change `substring(0, 12) ` to `substring(0, newdate.length - 3) `

**Comment by SLorant** [comment]
That's strange, can you provide an image of how it looks? Because in all of my devices they are in this format and look ok: 2023. 04. 02. I'm gonna send an image to show you. Also, the problem with showing the full string is that it's naturally a long date format (with timezone and everything).
![date1](https://user-images.githubusercontent.com/105773705/230762463-f8dae3e9-721a-4568-8786-be6d4b8de988.png)
![date2](https://user-images.githubusercontent.com/105773705/230762465-569de61c-119f-4a60-bed5-23d18cdb6d50.png)

**Comment by SharmaMitchell** [comment]
This is how it looks on my device (Chrome, desktop, en-US)
![image](https://user-images.githubusercontent.com/90817905/230790457-cfd42854-afc5-45ad-89d3-739325bcafc6.png)

I'd guess that it's because you're using toLocaleString without specifying a particular locale (ex. "en-US" or "en-GB"), here in Modal.jsx:
https://github.com/SLorant/Snowy-Snaps/blob/93c3f188a00ca79c83fc4de223397831718b7894/src/components/gallerycomp/Modal.jsx#L20-L22  

I can fork and look into it on my device. I think something like this (from the [official Luxon examples](https://moment.github.io/luxon/demo/global.html)) might do the trick: `DateTime.now().setLocale('zh').toLocaleString(DateTime.DATE_MED)` (swap 'zh' for 'en' of course)  

To clarify: I think specifying a particular locale would help keep the date formats consistent across different devices and locales. If locale is automatically set based on device/browser settings (as it is now), using substring will case strange behavior for some users.

**Comment by SLorant** [comment]
Thanks for the suggestion, now with these changes the formatting changed to like this: Apr 1, 2023. And with the set locale now it should look the same for everyone, but I wont close the issue until you verify that it looks good on your pc too.
```javascript
  const date = DateTime.fromSeconds(imgData.createdAt.seconds)
  const newDate = date.setLocale('en')
  const finaldate = newDate.toLocaleString(DateTime.DATE_MED)
```

**Comment by SharmaMitchell** [comment]
LGTM! Looks good on my end - Just PR'd since I noticed you hadn't pushed the change yet. Hope that's cool!  

UI from my pc:
![image](https://user-images.githubusercontent.com/90817905/230801974-c117f3ba-33e8-49f7-8cf0-683301e43314.png)
